### PR TITLE
Added inspect command (applies to items specifically), renamed choice…

### PR DESCRIPTION
**Pull request by ghost**
…s to aliases, added some new command aliases

### CODE REVIEW

**Comment by kauffecup** [comment]
look at you, being all javascripty. HOW DOES IT FEEL

**Comment by kauffecup** [comment]
hmm so here's the thing that i'm not really sure what this'll change

right now, `entities/Area.js` handles the `help`, `look`, and `repeat` commands. the area maintains the state from the parsed `.json` files and this way each area can respond differently to `look` without the main game loop needing to know about that. so that happens in: https://github.com/kauffecup/text-rpg-engine/blob/master/src/Game.js#L84

granted i'm not sure this is the best way to be doing that, and am totally open to changing that workflow.

right now the `look` command triggers the `Area.js` to print it's `_describe()` method: https://github.com/kauffecup/text-rpg-engine/blob/master/src/entities/Area.js#L92 which, in addition to the description, prints any doors and items that are chilling out

the two options i can think of are:
1. Instead of having your `_handleInspect` method return `respond(entityManager.get(itemID).description);`, have it return `....describe()`
2. Move your `_handleInspect` method to `Area.js`

Honestly I'm leaning towards #1 - it definitely is confusing that different things handle different regex parsing and it would be nice to have it all be in one spot

**Comment by kauffecup** [comment]
yeah the more i think about it, the first one seems like the way to go - so that would be changing your code from `.description` to the `.describe()` and then deleting the look regex as well as calling it from `Area.js`s `execute` function. so all in all a pretty tiny change - sorry for the essay above :)

**Comment by ghost** [comment]
Didn't realize items had a describe() function.

My intent with this was to allow "look" to give a description of the area, plus maybe flyby of everything in the room. Then, you could inspect an item for more verbose information, like "oh this key is gold an ornate, maybe it unlocks some massive door in a temple somewhere," like more info than we'd want in area.describe()

**Comment by ghost** [comment]
I don't understand why we'd delete the look regex, unless you think there's too much overlap between look and inspect.

**Comment by kauffecup** [comment]
:shipit:

**Pull request merged**
